{% set name = "PyLag" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

source:
  path: ..
  
requirements:
  host:
    - python
    - pip
    - openmpi
    - mpi4py
    - numpy>=1.20
    - cython>=0.29
  build:
    - python
    - {{ compiler('cxx') }}
  run:
    - python
    - mpi4py
    - numpy>=1.20
    - scipy>=1.4.1
    - cython>=0.29
    - progressbar
    - natsort
    - netCDF4
    - cftime>=1.1
    - configparser
    - stripy
    - shapely
    - pyproj
    - pytest

test:
  import:
    - pylag.main
    - pylag.parallel.main
  requires:
    - pytest
  source_files:
    - pylag/tests
  commands:
    - pytest

about:
  home: https://github.com/pmlmodelling/pylag
  license: GPL
  license_family: GPL
  summary: A particle tracking tool for marine applications
