{% set name = "PyLag" %}
{% set version = load_setup_py_data().get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vv 

source:
  path: ..
  
requirements:
  host:
    - python
    - pip
    - openmpi
    - mpi4py
    - numpy x.x
    - cython>=3.0
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - mpi4py
    - scipy>=1.4.1
    - cython>=3.0
    - progressbar
    - natsort
    - netCDF4
    - cftime>=1.1
    - configparser
    - stripy
    - shapely
    - pyproj
    - pytest

test:
  imports:
    - pylag.main
    - pylag.parallel.main
  requires:
    - pytest
  source_files:
    - pylag/tests
  commands:
    - pytest

about:
  home: https://github.com/pmlmodelling/pylag
  license: GPL
  license_family: GPL
  summary: A particle tracking tool for marine applications
