{% set name = "PyLag" %}
{% set version = load_setup_py_data().get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation"

source:
  path: ..
  
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - openmpi
    - mpi4py
    - numpy x.x
    - cython>=3.0
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - mpi4py
    - scipy>=1.4.1
    - progressbar
    - natsort
    - netcdf4
    - cftime>=1.1
    - configparser
    - stripy
    - shapely
    - pyproj

test:
  imports:
    - pylag.main
    - pylag.parallel.main
  requires:
    - pytest
  source_files:
    - pylag/tests
  commands:
    - pytest

about:
  home: https://github.com/pmlmodelling/pylag
  license: GPL
  license_family: GPL
  summary: A particle tracking tool for marine applications
