DEF FLOAT_ERR = -9999999.0
DEF INT_ERR = -9999999

DEF EPSILON = 1.0e-12
DEF N_VERTICES = 3
DEF N_NEIGH_ELEMS = 4

DEF IN_DOMAIN = 0
DEF LAND_BDY_CROSSED = -1
DEF OPEN_BDY_CROSSED = -2
DEF BDY_ERROR = -3
DEF IN_MASKED_ELEM = -4
DEF BOTTOM_BDY_CROSSED = -5
DEF IS_PERMANENTLY_BEACHED = -6

DEF DEFAULT_HOST = 0

DEF SEA = 0
DEF BOUNDARY_ELEMENT = 1
DEF LAND = 2
